stages:          # List of stages for jobs, and their order of execution
  - build
  - test

docker-build:       # This job runs in the build stage, which runs first.
  stage: build
  image: docker
  services:
    - docker:dind  # Enable Docker-in-Docker service
  variables:
    DOCKER_IMAGE_NAME: "start-docker-image"
    DOCKER_IMAGE_TAG: "latest"
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  script:
    - cd src/backend/backend
    - docker build -t ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG} .
    - docker push ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}

unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - echo "Running unit tests... This will take about 10 seconds."
    - sleep 10
    - echo "Code coverage is 90%"