stages:
  - build
  - test
    
django-build:
  stage: build
  only:
  - master
  - dev
  image: python:3.11
  before_script:
    - pip install Django
    - pip install requests
    - cd src/backend
    - echo "Starting Django server..."
    - Start-Process python -ArgumentList "manage.py runserver 8000" -NoNewWindow
    - sleep 20
  script:
    - echo "Full server statup process succesful."
    - echo "Shutting down server."
    - $process = Get-Process -Id (Get-NetTCPConnection -LocalPort 8000).OwningProcess
    - Stop-Process -ID $process.Id -Force
    - echo "Server shut down."

django-test:
  stage: test
  only:
  - master
  - dev
  image: python:3.11
  script:
    - echo "Starting backend test for Django server..."
    - cd src/backend
    - python manage.py test
    - echo "Backend test finished."
    - echo "Starting frontend test for Django server..."
    - npx jest
    - echo "Frontend test finished."

start-complete-test:
  stage: test
  only:
  - master
  - dev
  image: java:18
  script:
    - echo "Starting test for standard jar..."
    - cd src/start/CI-CD-testing/standard
    - ./test.sh
    - echo "Standard test finished."

    - echo "Starting test for debug jar..."
    - cd ../debug
    - ./test.sh
    - echo "Debug test finished."