stages:
  - build
    
django-build:
  stage: build
  only:
  - master
  - dev
  image: python:3.11
  before_script:
    - python -m pip install Django
    - pip install requests
    - cd src/backend
    - echo "Starting Django server..."
    - Start-Process python -ArgumentList "manage.py runserver 8000" -NoNewWindow
    - sleep 20
  script:
    - echo "Django server started. Init test..."
    - python manage.py test
    - echo "Test finished."
    - $process = Get-Process -Id (Get-NetTCPConnection -LocalPort 8000).OwningProcess
    - Stop-Process -ID $process.Id -Force
    - echo "Django server tests successful."

flask-build:
  stage: build
  only:
  - master
  - dev
  image: python:3.11
  before_script:
    - pip install Flask
    - cd src/backend/backend/app
    - echo "Starting Flask server..."
    - Start-Process python -ArgumentList "-m flask run --host 0.0.0.0 --port 80" -NoNewWindow
    - sleep 20
  script:
    - echo "Flask server started. Init test..."
    - echo "Test finished."
    - $process = Get-Process -Id (Get-NetTCPConnection -LocalPort 80).OwningProcess
    - Stop-Process -ID $process.Id -Force
    - echo "Django server tests successful."
