stages:
  - build
  - test

docker-build:
  stage: build
  image: docker
  services:
    - docker:dind
  variables:
    DOCKER_IMAGE_NAME: "start-docker-image"
    DOCKER_IMAGE_TAG: "latest"
  before_script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin docker.io
  script:
    - cd src/backend/backend
    - echo "Building docker image..."
    - docker build -t ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG} .
    - echo "Docker image built."
    - echo "Attempting to run docker image..."
    - docker run -d -p 80:80 ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}
    - echo "Docker image running."
    
django-build:
  stage: test
  image: python:3.6
  before_script:
    - python -m pip install Django
    - pip install requests
    - cd src/backend
    - echo "Starting server..."
    - Start-Process python -ArgumentList "manage.py runserver 8000" -NoNewWindow
    - sleep 20
  script:
    - echo "Server started. Init test..."
    - python manage.py test
    - echo "Test finished."
    - $process = Get-Process -Id (Get-NetTCPConnection -LocalPort 8000).OwningProcess
    - Stop-Process -ID $process.Id -Force
    - echo "Server stopped."
  