# Generated by Django 4.2.6 on 2024-02-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startwebapp', '0002_alter_session_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session',
            field=models.TextField(),
        ),
    ]
