# Generated by Django 4.2.6 on 2024-03-02 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startwebapp', '0003_alter_session_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 2, 15, 56, 53, 813720, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='session',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='session',
            name='title',
            field=models.CharField(default='Untitled', max_length=50),
        ),
    ]
